// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN7nCwLTDqCYMTmFZ77vB5VVzAh9WEjkA',
    appId: '1:404706246506:web:b7a7c5fdbd0c7e3a252f13',
    messagingSenderId: '404706246506',
    projectId: 'remithub-7ed26',
    authDomain: 'remithub-7ed26.firebaseapp.com',
    storageBucket: 'remithub-7ed26.firebasestorage.app',
    measurementId: 'G-RNWY7ET9HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBecjOZeWZSnJRBN-iY7DYufCQ6ZSnDxfs',
    appId: '1:404706246506:android:1361eb6f3dd0c665252f13',
    messagingSenderId: '404706246506',
    projectId: 'remithub-7ed26',
    storageBucket: 'remithub-7ed26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB__28GKbYWWYp_lTXns6FUzU49mKc935g',
    appId: '1:404706246506:ios:58266114279f8dc5252f13',
    messagingSenderId: '404706246506',
    projectId: 'remithub-7ed26',
    storageBucket: 'remithub-7ed26.firebasestorage.app',
    iosBundleId: 'com.example.weweremit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB__28GKbYWWYp_lTXns6FUzU49mKc935g',
    appId: '1:404706246506:ios:58266114279f8dc5252f13',
    messagingSenderId: '404706246506',
    projectId: 'remithub-7ed26',
    storageBucket: 'remithub-7ed26.firebasestorage.app',
    iosBundleId: 'com.example.weweremit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN7nCwLTDqCYMTmFZ77vB5VVzAh9WEjkA',
    appId: '1:404706246506:web:05e4f70dadb2cb71252f13',
    messagingSenderId: '404706246506',
    projectId: 'remithub-7ed26',
    authDomain: 'remithub-7ed26.firebaseapp.com',
    storageBucket: 'remithub-7ed26.firebasestorage.app',
    measurementId: 'G-Z0D8Y1RZFL',
  );
}
